services:
  ingoschindler:
    image: nginx:1-alpine
    expose:
      - 80
    volumes:
      - ./ingoschindler.de/:/usr/share/nginx/html
      - ./nginx-status.conf:/etc/nginx/conf.d/default.conf:ro
      - logs_ingoschindler:/var/log/nginx
    networks:
      - proxy
      - nginx-internal

  hausschindler:
    image: nginx:1-alpine
    expose:
      - 80
    volumes:
      - ./hausschindler.de/:/usr/share/nginx/html
      - ./nginx-status.conf:/etc/nginx/conf.d/default.conf:ro
      - logs_hausschindler:/var/log/nginx
    networks:
      - proxy
      - nginx-internal

  sashriti-homepage:
    image: nginx:1-alpine
    expose:
      - 80
    volumes:
      - ./sashriti.com/:/usr/share/nginx/html
      - ./nginx-status.conf:/etc/nginx/conf.d/default.conf:ro
      - logs_sashriti:/var/log/nginx
    networks:
      - proxy
      - nginx-internal

  ingoschindler-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: --nginx.scrape-uri=http://ingoschindler/stub_status
    expose:
      - 9113
    networks:
      - nginx-internal
      - monitoring

  hausschindler-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: --nginx.scrape-uri=http://hausschindler/stub_status
    expose:
      - 9113
    networks:
      - nginx-internal
      - monitoring

  sashriti-homepage-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: --nginx.scrape-uri=http://sashriti-homepage/stub_status
    expose:
      - 9113
    networks:
      - nginx-internal
      - monitoring

  goaccess-ingoschindler:
    image: allinurl/goaccess:latest
    command: >
      /var/log/nginx/access.log
      --config-file=/etc/goaccess/goaccess.conf
      --output=/srv/report/index.html
      --real-time-html
      --port=7890
    volumes:
      - logs_ingoschindler:/var/log/nginx:ro
      - ./goaccess-ingoschindler.conf:/etc/goaccess/goaccess.conf:ro
      - report_ingoschindler:/srv/report
    expose:
      - 7890
    networks:
      - proxy

  goaccess-hausschindler:
    image: allinurl/goaccess:latest
    command: >
      /var/log/nginx/access.log
      --config-file=/etc/goaccess/goaccess.conf
      --output=/srv/report/index.html
      --real-time-html
      --port=7890
    volumes:
      - logs_hausschindler:/var/log/nginx:ro
      - ./goaccess-hausschindler.conf:/etc/goaccess/goaccess.conf:ro
      - report_hausschindler:/srv/report
    expose:
      - 7890
    networks:
      - proxy

  goaccess-sashriti:
    image: allinurl/goaccess:latest
    command: >
      /var/log/nginx/access.log
      --config-file=/etc/goaccess/goaccess.conf
      --output=/srv/report/index.html
      --real-time-html
      --port=7890
    volumes:
      - logs_sashriti:/var/log/nginx:ro
      - ./goaccess-sashriti.conf:/etc/goaccess/goaccess.conf:ro
      - report_sashriti:/srv/report
    expose:
      - 7890
    networks:
      - proxy

volumes:
  logs_ingoschindler:
  logs_hausschindler:
  logs_sashriti:
  report_ingoschindler:
  report_hausschindler:
  report_sashriti:

networks:
  proxy:
    external: true
    name: schindler_net
  monitoring:
    external: true
    name: sashriti_monitoring
  nginx-internal:
    driver: bridge
