map $http_user_agent $loggable {
    ~*NGINX-Prometheus-Exporter 0;
    default 1;
}

server {
    listen 80;
    real_ip_header X-Real-IP;
    set_real_ip_from 172.16.0.0/12;
    log_format realip '$remote_addr XFF=$http_x_forwarded_for XRI=$http_x_real_ip [$time_local] "$request"';
    access_log /var/log/nginx/access.log realip if=$loggable;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    location /stub_status {
        stub_status;
        allow 127.0.0.1;
        allow 172.0.0.0/8;
        deny all;
    }
}
